% generated by AI for copying, no letter escaped

function fcn_edgeMapper_plot_mapper(subject, parcellation, session, simplex, input_directory, output_directory, varargin)
    % Replot Mapper graph with new aesthetic parameters
    %
    % Loads previously computed Mapper results and regenerates visualization
    % with different aesthetic settings without recomputing the graph structure.
    %
    % Inputs:
    %   subject - Subject ID number (e.g., 100206)
    %   parcellation - Parcellation name (e.g., "schaefer100x7")
    %   session - Session identifier: "LR" or "RL"
    %   simplex - Feature type: "node", "edge", or "triangle"
    %   output_directory - Directory containing saved data and for new output
    %
    % Optional Parameters (name-value pairs):
    %   'input_filename_prefix' - Prefix for input data file (default: "simplexMapper")
    %   'output_filename_prefix' - Prefix for output file (default: same as input_filename_prefix)
    %   'output_filename_suffix' - Suffix to add to output filename (default: "")
    %                              Example: "_new_aesthetics" produces files like
    %                              simplexMapper_edge_100206_LR_schaefer100x7_new_aesthetics.pdf
    %
    %   'edge_color' - RGB or RGBA color for edges (default: [0.6, 0.6, 0.6])
    %   'edge_alpha' - Alpha transparency for edges (default: 0.3)
    %                  Ignored if edge_color has 4 elements
    %   'node_alpha' - Alpha transparency for nodes (default: 0.9)
    %   'minimal_radius' - Minimum node radius (default: 0.1)
    %   'radius_scaling_factor' - Scaling factor for node sizes (default: 2)
    %   'colorbar_flag' - Show colorbar: 1=yes, 0=no (default: 1)
    %   'highlighted_nodes' - Vector of node indices to highlight (default: [])
    %   'highlighted_sectors' - [nodes x tasks] binary matrix (default: [])
    %   'use_saved_positions' - Use saved node positions: 1=yes, 0=no (default: 1)
    %
    % Outputs (no return values):
    %   Files created:
    %     - <output_filename_prefix>_<simplex>_<subject>_<session>_<parcellation><suffix>.pdf
    %
    % Example:
    %   fcn_edgeMapper_replot_mapper(100206, "schaefer100x7", "LR", "edge", "/path/to/output", ...
    %       'output_filename_suffix', '_high_contrast', ...
    %       'edge_alpha', 0.5, ...
    %       'node_alpha', 0.8, ...
    %       'minimal_radius', 0.15);
    %
    % See also: fcn_edgeMapper_compute_and_analyze_simplex_mapper, fcn_mapper_drawd3graph
    
    %% Parse inputs
    
    p = inputParser;
    addRequired(p, 'subject', @isnumeric);
    addRequired(p, 'parcellation', @(x) isStringScalar(x) || ischar(x));
    addRequired(p, 'session', @(x) isStringScalar(x) || ischar(x));
    addRequired(p, 'simplex', @(x) isStringScalar(x) || ischar(x));
    addRequired(p, 'input_directory', @(x) isStringScalar(x) || ischar(x));
    addRequired(p, 'output_directory', @(x) isStringScalar(x) || ischar(x));
    
    % File naming
    addParameter(p, 'input_filename_prefix', 'simplexMapper', @(x) isStringScalar(x) || ischar(x));
    addParameter(p, 'output_filename_prefix', '', @(x) isStringScalar(x) || ischar(x));
    addParameter(p, 'output_filename_suffix', '', @(x) isStringScalar(x) || ischar(x));
    
    % Aesthetic parameters
    addParameter(p, 'edge_color', [0.6, 0.6, 0.6], @isnumeric);
    addParameter(p, 'edge_alpha', 0.3, @isnumeric);
    addParameter(p, 'node_alpha', 0.9, @isnumeric);
    addParameter(p, 'minimal_radius', 0.1, @isnumeric);
    addParameter(p, 'radius_scaling_factor', 2, @isnumeric);
    addParameter(p, 'colorbar_flag', 1, @isnumeric);
    addParameter(p, 'highlighted_nodes', [], @isnumeric);
    addParameter(p, 'highlighted_sectors', [], @isnumeric);
    
    % Data parameters
    addParameter(p, 'use_saved_positions', 1, @isnumeric);
    
    parse(p, subject, parcellation, session, simplex, input_directory, output_directory, varargin{:});
    
    % Extract parameters
    parcellation = string(p.Results.parcellation);
    session = string(p.Results.session);
    simplex = string(p.Results.simplex);
    input_directory = string(p.Results.input_directory);
    output_directory = string(p.Results.output_directory);
    input_filename_prefix = string(p.Results.input_filename_prefix);
    output_filename_prefix = string(p.Results.output_filename_prefix);
    output_filename_suffix = string(p.Results.output_filename_suffix);
    edge_color = p.Results.edge_color;
    edge_alpha = p.Results.edge_alpha;
    node_alpha = p.Results.node_alpha;
    minimal_radius = p.Results.minimal_radius;
    radius_scaling_factor = p.Results.radius_scaling_factor;
    colorbar_flag = p.Results.colorbar_flag;
    highlighted_nodes = p.Results.highlighted_nodes;
    highlighted_sectors = p.Results.highlighted_sectors;
    use_saved_positions = p.Results.use_saved_positions;
    
    % Set output prefix to input prefix if not specified
    if strlength(output_filename_prefix) == 0
        output_filename_prefix = input_filename_prefix;
    end
    
    %% Build file paths
    
    % Input data file: <prefix>_<simplex>_<subject>_<session>_<parcellation>_data.mat
    input_filename_base = sprintf("%s_%s_%d_%s_%s", input_filename_prefix, simplex, subject, session, parcellation);
    data_filename = fullfile(input_directory, strcat(input_filename_base, "_data.mat"));
    
    % Output plot file: <prefix>_<simplex>_<subject>_<session>_<parcellation><suffix>
    output_filename_base = sprintf("%s_%s_%d_%s_%s%s", output_filename_prefix, simplex, subject, session, parcellation, output_filename_suffix);
    output_filename = fullfile(output_directory, output_filename_base);
    
    %% Load data
    
    fprintf('Loading data from: %s\n', data_filename);
    
    if ~isfile(data_filename)
        error('Data file not found: %s\nExpected format: <prefix>_<simplex>_<subject>_<session>_<parcellation>_data.mat', data_filename);
    end
    
    loaded_data = load(data_filename);
    
    % Check for required variables
    required_vars = {'mapper_nodeBynode', 'mapper_stat_mode_task_indices', 'mapper_stat_task_count_per_node', 'feature_tasks_instantwise'};
    for i = 1:numel(required_vars)
        if ~isfield(loaded_data, required_vars{i})
            error('Required variable "%s" not found in data file', required_vars{i});
        end
    end
    
    % Extract required variables
    mapper_nodeBynode = loaded_data.mapper_nodeBynode;
    mapper_stat_mode_task_indices = loaded_data.mapper_stat_mode_task_indices;
    mapper_stat_task_count_per_node = loaded_data.mapper_stat_task_count_per_node;
    feature_tasks_instantwise = loaded_data.feature_tasks_instantwise;
    
    %% Reconstruct tasks_string
    
    % Standard task ordering (without REST)
    tasks_string = ["EMOTION", "GAMBLING", "LANGUAGE", "MOTOR", "RELATIONAL", "SOCIAL", "WM"];
    
    % Check if REST is included by counting unique tasks
    num_unique_tasks = numel(unique(feature_tasks_instantwise));
    if num_unique_tasks == 8
        tasks_string = ["REST", tasks_string];
        fprintf('  Detected 8 tasks: including REST\n');
    else
        fprintf('  Detected %d tasks: no REST\n', num_unique_tasks);
    end
    
    %% Get node positions
    
    if use_saved_positions && isfield(loaded_data, 'mapper_nodes_positions')
        XY = loaded_data.mapper_nodes_positions;
        fprintf('  Using saved node positions\n');
    else
        XY = [];
        fprintf('  Computing new node positions\n');
    end
    
    %% Get colormap
    
    cmap = fcn_utils_get_task_coloring(tasks_string);
    
    %% Construct edge color with alpha
    
    if numel(edge_color) == 4
        edge_color_with_alpha = edge_color;
    else
        edge_color_with_alpha = [edge_color(:)', edge_alpha];
    end
    
    %% Plot
    
    fprintf('Generating plot...\n');
    
    % Call plotting function
    fcn_mapper_drawd3graph(mapper_nodeBynode, mapper_stat_mode_task_indices, cmap, ...
        output_filename, mapper_stat_task_count_per_node, ...
        'XY', XY, ...
        'labels', tasks_string, ...
        'minimal_radius', minimal_radius, ...
        'radius_scaling_factor', radius_scaling_factor, ...
        'colorbar_flag', colorbar_flag, ...
        'highlighted_nodes', highlighted_nodes, ...
        'highlighted_sectors', highlighted_sectors, ...
        'edge_alpha', edge_color_with_alpha(4), ...
        'node_alpha', node_alpha);
    
    fprintf('Plot saved to: %s.pdf\n', output_filename);
    
end