% generated by AI for copying, no letter escaped

% Script to replot mapper graphs with new edge alpha
%
% Loops over subjects and simplex types to regenerate visualizations
% with edge_alpha = 0.6, saving with suffix "_edgeAlpha_60"

%% Define parameters

subjects = [
    100206, ...
    125525, ...
    144832, ...
    192641, ...
    725751
];

session = "LR";
parcellation = "schaefer100x7";
simplices = ["node", "edge", "triangle"];

% Output directory (adjust as needed)
config = fcn_utils_get_config();

output_directory = fullfile(config.repo_root, "data_pipeline/individual_mapper_graphs");

% New aesthetic parameters
edge_alpha = 0.6;
output_suffix = "_edgeAlpha_60";

%% Loop over subjects and simplex types

fprintf('========================================\n');
fprintf('Replotting Mapper Graphs\n');
fprintf('========================================\n');
fprintf('Edge alpha: %.1f\n', edge_alpha);
fprintf('Output suffix: %s\n', output_suffix);
fprintf('Session: %s\n', session);
fprintf('Parcellation: %s\n', parcellation);
fprintf('Subjects: %s\n', mat2str(subjects));
fprintf('Simplex types: %s\n', strjoin(simplices, ', '));
fprintf('========================================\n\n');

total_plots = numel(subjects) * numel(simplices);
current_plot = 0;

for subj_idx = 1:numel(subjects)
    subject = subjects(subj_idx);
    
    for simp_idx = 1:numel(simplices)
        current_simplex = simplices(simp_idx);
        current_plot = current_plot + 1;
        
        fprintf('[%d/%d] Processing subject %d, simplex %s...\n', ...
                current_plot, total_plots, subject, current_simplex);
        
        input_directory = fullfile(config.scratch_dir, sprintf("simplex_mapper_raw_features_cohort_one_LR_%s_schaefer100x7/", current_simplex));

        try
            fcn_edgeMapper_plot_mapper(subject, parcellation, session, current_simplex, input_directory, output_directory, ...
                'edge_alpha', edge_alpha, ...
                'output_filename_suffix', output_suffix);
            fprintf('  Success!\n\n');
        catch ME
            fprintf('  ERROR: %s\n', ME.message);
            fprintf('  Skipping...\n\n');
        end
    end
end

fprintf('========================================\n');
fprintf('Replotting Complete\n');
fprintf('========================================\n');